import { useEffect, useState, useRef } from "react";
import Head from "next/head";
import AgeModal from "../components/AgeModal";
import RandomCocktail from "../../components/RandomCocktail";

const Index = () => {
  return (
    <>
      <Head>
        <title>Mixology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <RandomCocktail />
    </>
  );
};

export default Index;
