import Head from "next/head";
import AgeModal from "../components/AgeModal";
import DefaultCocktails from "../../components/DefaultCocktails";
import RandomCocktail from "../../components/RandomCocktail";
import ScrollToTopButton from "../../components/ScrollToTopButton";

const Index = () => {
  return (
    <>
      <Head>
        <title>Drinktionary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <DefaultCocktails />
      <RandomCocktail />
      <AgeModal />
      <ScrollToTopButton></ScrollToTopButton>
    </>
  );
};

export default Index;
